header was created
mate-academy/layout_creativeBakery pull request #211
Opened 2022-06-27 15:06 UTC by katerinahradinarova

[DEMO LINK](https://katerinahradinarova.github.io/layout_creativeBakery/)

2022-07-01 08:07 UTC, ivan-kadykalo requested changes
1. Іконки соц мереж мають вести на соцмережі в новій вкладці

2. Виглядає не по макету
![image](https://user-images.githubusercontent.com/57747481/176852583-013934f5-7925-4eb5-8d2f-5af61daffe29.png)

3. Мобілка перший екран
![image](https://user-images.githubusercontent.com/57747481/176852694-f58c99ef-8d0a-462e-a377-31960892deee.png)

2022-07-01 09:10 UTC, katerinahradinarova commented
дякую! пофіксила

2022-07-01 10:05 UTC, ivan-kadykalo requested changes
Відтестуй вигляд сайту на всіх розширеннях. 
1. На планшеті екран виглядає дуже пустим, спробуй відцентрувати елементи, глянь ще раз макет.
![image](https://user-images.githubusercontent.com/57747481/176873532-4f0eba6b-b799-4f7e-b615-64d0a9e29ca6.png)

2. На мобілі iphone se не вміщається кнопка на першому екрані
![image](https://user-images.githubusercontent.com/57747481/176873566-c2cde92f-d14a-45f5-97f4-7d8559ec9141.png)

3. На десктопі виглядає що перший екран захардкоджено, для більшого розширення вже видно нижні блоки
![image](https://user-images.githubusercontent.com/57747481/176873753-cc1032a5-9d4a-4100-91ea-d9862b9e6fa5.png)

2022-07-15 08:28 UTC, ivan-kadykalo requested changes
Схоже що планшет та телефон так і не виправленні. Дуже багато пустого місця.
![image](https://user-images.githubusercontent.com/57747481/179184686-2a1796b8-eb6c-47fe-93ec-0a09a3df9146.png)
![image](https://user-images.githubusercontent.com/57747481/179184730-9f5b431b-a6a2-45f0-87f1-551bb73974be.png)

2022-07-15 14:06 UTC, katerinahradinarova commented
дякую! здається, виправила...

2022-07-15 14:06 UTC, closed without merging

2022-07-15 14:11 UTC, ivan-kadykalo approved these changes