Develop
mate-academy/layout_creativeBakery pull request #233
Opened 2022-07-27 16:59 UTC by tiserett

[DEMO LINK](https://tiserett.github.io/layout_creativeBakery/).

2022-08-01 13:57 UTC, AlinaMatuschak requested changes
- add hovers
<img width="195" alt="Screenshot 2022-08-01 at 16 16 34" src="https://user-images.githubusercontent.com/47606379/182156397-715b4a0e-18a4-4b30-a20b-40994853cc1e.png">

- "learn more" btn does nothing. Add scroll to some block 
- check spaces between blocks
- you can centralize vertically icon with text (looks broken)
<img width="156" alt="Screenshot 2022-08-01 at 16 28 13" src="https://user-images.githubusercontent.com/47606379/182158588-961e8168-e266-405b-9d62-5cc6a0437aa0.png">

- I can’t see all mobile menu, Scroll doesn’t work, and I don’t see all links
<img width="617" alt="Screenshot 2022-08-01 at 16 56 53" src="https://user-images.githubusercontent.com/47606379/182164196-bd0d7cee-d801-4692-9c3a-c9fc42626cae.png">

2022-08-02 14:47 UTC, AlinaMatuschak approved these changes
GJ 🔥

- add hovers
<img width="283" alt="Screenshot 2022-08-02 at 17 39 57" src="https://user-images.githubusercontent.com/47606379/182401900-efd023ab-e38e-4c74-970e-ddabb6f58fed.png">

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/index.html
> +            <article class="card card-1">
nth-child

```suggestion
            <article class="card">
```

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/index.html
> +                class="card__img">
```suggestion
            <article class="card card-3">
              <img
                src="./images/content/product3.png"
                alt="cake"
                class="card__img"
              >
```

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/index.html
> +            <article class="about__info about__info-1">
```suggestion
            <article class="about__info">
```

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/styles/blocks/footer.scss
> +      transition: all 0.3s;
Always add transition property. Hard for the browser to control all properties

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/styles/blocks/footer.scss
> +      transition: all 0.3s;
you can create variable for 0.3s

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/styles/blocks/main/products.scss
> +  margin-bottom: 80px;
Margin for bem block?

2022-08-02 14:47 UTC, AlinaMatuschak commented on src/styles/blocks/page.scss
> +}
It shouldn’t be on the page file. Create normalize and reset

2022-08-02 16:38 UTC, tiserett commented on src/index.html
> +            <article class="about__info about__info-1">
I can't rewrite it with nth-child, so I'll leave it like this, but I fixed cards. idk why it's not working ;(

2024-03-09 11:21 UTC, closed without merging