Develop
mate-academy/layout_creativeBakery pull request #8
Opened 2021-02-03 12:14 UTC by Jastler

[DEMO LINK](https://jastler.github.io/layout_creativeBakery/)

2021-02-03 13:24 UTC, bogdandobak commented
відступи різні https://prnt.sc/y5grdv

2021-02-03 13:30 UTC, bogdandobak requested changes

2021-02-03 13:30 UTC, bogdandobak commented on src/index.html
> +              Contacts
зроби навігацію по сайту

2021-02-03 13:30 UTC, bogdandobak commented on src/index.html
> +        <a class="main-info__button big-button" href="#">
переноси

2021-02-03 13:30 UTC, bogdandobak commented on src/index.html
> +              </div>
тут також переноси і дальше також подивись

2021-02-03 16:11 UTC, bogdandobak approved these changes

2021-02-05 12:08 UTC, Vladimir-Beliy commented
ui супер)

2021-02-05 12:17 UTC, Vladimir-Beliy requested changes

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/index.html
> +              class="side-info__link phone__icon fas fa-phone-alt"
"side-info__link phone__icon fas fa-phone-alt"
не может быть два элемента
что такое fa-phone-alt и fas? (непонятные названия)

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/index.html
> +                  <p class="fas fa-chevron-right"></p>
не понимаю что такое fas и fa

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/_typography.scss
> +@media screen and (max-width: 1025px) {
давай вынесем breakpoints в переменные

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/header/logo.scss
> +    content: url("data:image/svg+xml;charset=UTF-8,%3csvg width='41' height='42' viewBox='0 0 41 42' fill='none' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M20.5 0C9.17819 0 0 9.18203 0 20.5086C
что это?

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/header/logo.scss
> +    content: url("data:image/svg+xml;charset=UTF-8,%3csvg width='41' height='42' viewBox='0 0 41 42' fill='none' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M0 20.5086C0 9.18203 9.17819 0 20.5 0C
подключи с файла

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/header/side-info.scss
> +.side-info.active,
слектор не по бем

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/header/side-info.scss
> +}
эти элементы не должны быть здесь

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/product/product.scss
> +  }
очень странный селектор

2021-02-05 12:17 UTC, Vladimir-Beliy commented on src/styles/product/product.scss
> +    }
какие элементы выбирает этот &__card:nth-child(n) &__item?

2021-02-08 12:25 UTC, solaryasha reviewed
Не думаю, що так було задумано
<img width="524" alt="Screenshot 2021-02-08 at 14 25 13" src="https://user-images.githubusercontent.com/32794096/107219337-9adf8a80-6a19-11eb-9068-af5088e57efb.png">

2021-02-08 12:32 UTC, solaryasha requested changes
Хороша робота, давай зробимо її ідеальною

2021-02-08 12:32 UTC, solaryasha commented on src/index.html
> +            >
```suggestion
            <select 
              class="side-info__select"
              id="lang"
              name="lang"
            >
```

2021-02-08 12:32 UTC, solaryasha commented on src/styles/burger.scss
> +    transition: all 0.2s linear;
Явно вказуй які властивості анімуєш
```suggestion
    transition: all 0.2s linear;
```

2021-02-08 12:32 UTC, solaryasha commented on src/styles/buttons.scss
> +.big-button {
Розбий на два файли

2021-02-08 12:32 UTC, solaryasha commented on src/styles/footer.scss
> +  color: white;
Кілька разів повторюється, тому винеси в змінну

2021-02-08 12:32 UTC, solaryasha commented on src/styles/header.scss
> +    }
Запиши ці правила в `menu` блоці

2021-02-08 12:32 UTC, solaryasha commented on src/styles/header.scss
> +      .menu {
Ці теж

2021-02-08 12:32 UTC, solaryasha commented on src/styles/side-info.scss
> +
Не залишай такі відступи

2021-02-08 12:32 UTC, solaryasha commented on src/styles/slides.scss
> +  margin-right: 80px;
Бем блок і зовнішні відступи

2021-02-08 13:21 UTC, solaryasha requested changes

2021-02-08 13:21 UTC, solaryasha commented on src/styles/menu.scss
> +  .header {
Не підвищуй специфічність класів
Застосуй правила для `menu__list`

2021-02-08 13:28 UTC, Jastler commented on src/styles/menu.scss
> +  .header {
Если я сделаю просто для `menu__list`, то у меня применится и для меню в футере

2021-02-08 13:49 UTC, solaryasha commented on src/styles/menu.scss
> +  .header {
Для цього і придумали BEM, щоб такого не було

2021-02-08 13:54 UTC, solaryasha commented on src/styles/menu.scss
> +      transition: all 0.2s;
Не виправив комент, явно вказуй які властивості застосовуй

2021-02-08 18:47 UTC, solaryasha approved these changes

2021-02-08 18:48 UTC, solaryasha reviewed
На великих екранах з'являється білий фон
<img width="1099" alt="Screenshot 2021-02-08 at 20 48 02" src="https://user-images.githubusercontent.com/32794096/107267011-faa45880-6a4e-11eb-94ad-50c91b339c87.png">

2021-02-09 05:28 UTC, solaryasha reviewed
Тепер контент розтягується, хоча немає. Можеш background фотку розтягнути на весь екран, а контенту задати max-width 
<img width="1091" alt="Screenshot 2021-02-09 at 07 25 22" src="https://user-images.githubusercontent.com/32794096/107319857-49321100-6aa8-11eb-9034-829bc256f7b4.png">

2021-02-09 08:36 UTC, solaryasha approved these changes
Good !

2026-05-12 17:03 UTC, closed without merging